apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-report-ingress
  namespace: traffic-report
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-global-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dds.dominikh.eu
        - www.dds.dominikh.eu
      secretName: traffic-report-certificate
  rules:
    - host: dds.dominikh.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traffic-report-service
                port:
                  number: 8000
    - host: www.dds.dominikh.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traffic-report-service
                port:
                  number: 8000
