apiVersion: v1
kind: Service
metadata:
  name: traffic-report-service
  namespace: traffic-report
spec:
  selector:
    app: traffic-report
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP